name: CI
on:
  [push]
jobs:
  setup_lint_test:
    name: Demo Cache
    runs-on: macos-10.15
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: clean node_modules
        run: rm -rf ./node_modules
      - uses: actions/cache@v2
        id: node-modules-cache # use this to check for `cache-hit` (`steps.node-modules-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - name: Yarn Install (with ./node_modules cached)
        if: steps.${{ runner.os }}-node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: clean node_modules
        run: rm -rf ./node_modules
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Yarn Install (using yarn cache)
        if: steps.${{ runner.os }}-node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install